ALIASING: USED TO GIVE ALTERNATE NAME TO OBJECTS & COLUMN_NAME.
-----------
1) TABLE ALIAS
 
             SELECT XX.NAME VENDOR_NAME FROM XX_SUPPLIER XX; --XX IS TABLE ALIAS

2) COLUMN ALIAS
 
  SELECT XX.NAME VENDOR_NAME FROM XX_SUPPLIER XX;           --VENDOR_NAME IS COLUMN ALIAS

