RULES FOR CREATING TABLE: 
-----------------------
 1)TABLE NAME MUST BE UNIQUE.
 
 2)TABLE NAME MAX LENGTH =30 CHARACTORS.
 
 3)A TABLE CAN CONTAINS MAX 1000 COLUMNS AND UNLIMITED ROWS.
 
 4)ATTRIBUTE NAME OF TABLE MUST BE UNIQUE.
 
 5)A IDENTIFIERS CONTAINS LETTERS(UPPPER AND LOWER CASE),DIGITS(0-9) AND SPECIAL CHARACTOR($,#,_)
 
 6)CAN NOT START WITH NUMBERS ,CAN START WITH LETTERS AND (_)UNDERSCORES ONLY.
 
 7)IDENTIFIER MEANS USER DEFINED (TABLE_NAME OR COLUMN_NAME)
 
 8)SQL KEYWORDS NOT ALLOWED AS IDENTIFIERS
 
 9)ORACLE SQL IS CASE INSENSITIVE.
 ----------------------------------------------------------------------
 